import { useState, useEffect } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../db';
import type { Task, Plant } from '../types';
import { format, isAfter, isBefore, parseISO } from 'date-fns';
import {
  LayoutDashboard,
  Plus,
  CheckCircle2,
  Circle,
  AlertTriangle,
  Clock,
  Leaf,
  Sprout,
  X,
  CalendarDays,
} from 'lucide-react';

function toCurrentYearDate(mmdd: string): Date {
  const year = new Date().getFullYear();
  const [month, day] = mmdd.split('-').map(Number);
  return new Date(year, month - 1, day);
}

interface AutoReminder {
  id: string;
  title: string;
  plantId: number;
  type: 'sow-indoor' | 'sow-direct' | 'transplant' | 'harvest';
  dueDate: Date;
}

function generateAutoReminders(plants: Plant[]): AutoReminder[] {
  const today = new Date();
  const reminders: AutoReminder[] = [];

  for (const plant of plants) {
    if (!plant.id) continue;

    if (plant.sowIndoorRange) {
      const start = toCurrentYearDate(plant.sowIndoorRange.start);
      const end = toCurrentYearDate(plant.sowIndoorRange.end);
      if (
        (isBefore(today, end) || today.toDateString() === end.toDateString()) &&
        (isAfter(today, start) || today.toDateString() === start.toDateString())
      ) {
        reminders.push({
          id: `auto-sow-indoor-${plant.id}`,
          title: `Time to sow ${plant.name} indoors`,
          plantId: plant.id,
          type: 'sow-indoor',
          dueDate: start,
        });
      }
    }

    if (plant.sowDirectRange) {
      const start = toCurrentYearDate(plant.sowDirectRange.start);
      const end = toCurrentYearDate(plant.sowDirectRange.end);
      if (
        (isBefore(today, end) || today.toDateString() === end.toDateString()) &&
        (isAfter(today, start) || today.toDateString() === start.toDateString())
      ) {
        reminders.push({
          id: `auto-sow-direct-${plant.id}`,
          title: `Time to direct sow ${plant.name}`,
          plantId: plant.id,
          type: 'sow-direct',
          dueDate: start,
        });
      }
    }

    if (plant.transplantRange) {
      const start = toCurrentYearDate(plant.transplantRange.start);
      const end = toCurrentYearDate(plant.transplantRange.end);
      if (
        (isBefore(today, end) || today.toDateString() === end.toDateString()) &&
        (isAfter(today, start) || today.toDateString() === start.toDateString())
      ) {
        reminders.push({
          id: `auto-transplant-${plant.id}`,
          title: `Time to transplant ${plant.name}`,
          plantId: plant.id,
          type: 'transplant',
          dueDate: start,
        });
      }
    }

    if (plant.harvestRange) {
      const start = toCurrentYearDate(plant.harvestRange.start);
      const end = toCurrentYearDate(plant.harvestRange.end);
      if (
        (isBefore(today, end) || today.toDateString() === end.toDateString()) &&
        (isAfter(today, start) || today.toDateString() === start.toDateString())
      ) {
        reminders.push({
          id: `auto-harvest-${plant.id}`,
          title: `Harvest time for ${plant.name}`,
          plantId: plant.id,
          type: 'harvest',
          dueDate: start,
        });
      }
    }
  }

  return reminders;
}

export default function DashboardPage() {
  const [showAddForm, setShowAddForm] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newDueDate, setNewDueDate] = useState('');

  const tasks = useLiveQuery(() => db.tasks.toArray()) ?? [];
  const plants = useLiveQuery(() => db.plants.toArray()) ?? [];

  const [autoReminders, setAutoReminders] = useState<AutoReminder[]>([]);

  useEffect(() => {
    if (plants.length > 0) {
      setAutoReminders(generateAutoReminders(plants));
    }
  }, [plants]);

  const today = new Date();
  const todayStr = format(today, 'yyyy-MM-dd');

  const overdueTasks = tasks.filter(
    (t) => !t.completed && t.dueDate && isBefore(parseISO(t.dueDate), today) && t.dueDate < todayStr
  );
  const todayTasks = tasks.filter(
    (t) => !t.completed && t.dueDate === todayStr
  );
  const upcomingTasks = tasks.filter(
    (t) => !t.completed && t.dueDate && t.dueDate > todayStr
  );
  const completedTasks = tasks.filter((t) => t.completed);
  const noDueDateTasks = tasks.filter((t) => !t.completed && !t.dueDate);

  const handleAddTask = async () => {
    if (!newTitle.trim()) return;
    await db.tasks.add({
      title: newTitle.trim(),
      dueDate: newDueDate || undefined,
      completed: false,
      isAutoGenerated: false,
    });
    setNewTitle('');
    setNewDueDate('');
    setShowAddForm(false);
  };

  const toggleTask = async (task: Task) => {
    if (task.id) {
      await db.tasks.update(task.id, { completed: !task.completed });
    }
  };

  const deleteTask = async (taskId: number) => {
    await db.tasks.delete(taskId);
  };

  const reminderIcon = (type: AutoReminder['type']) => {
    switch (type) {
      case 'sow-indoor':
        return <Sprout className="w-4 h-4 text-yellow-600" />;
      case 'sow-direct':
        return <Leaf className="w-4 h-4 text-green-600" />;
      case 'transplant':
        return <Sprout className="w-4 h-4 text-blue-600" />;
      case 'harvest':
        return <Leaf className="w-4 h-4 text-orange-600" />;
    }
  };

  return (
    <div className="p-4 max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <LayoutDashboard className="w-6 h-6 text-green-700 dark:text-green-400" />
          <h1 className="text-2xl font-bold text-green-900 dark:text-green-100">
            Dashboard
          </h1>
        </div>
        <button
          onClick={() => setShowAddForm(true)}
          className="flex items-center gap-1 px-3 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm font-medium transition-colors"
        >
          <Plus className="w-4 h-4" />
          Add Task
        </button>
      </div>

      {/* Add Task Form */}
      {showAddForm && (
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-green-200 dark:border-green-800 p-4 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-semibold text-green-800 dark:text-green-200">
              New Task
            </h3>
            <button
              onClick={() => setShowAddForm(false)}
              className="text-gray-400 hover:text-gray-600"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
          <div className="space-y-3">
            <input
              type="text"
              placeholder="Task title..."
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleAddTask()}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none"
              autoFocus
            />
            <div className="flex items-center gap-3">
              <input
                type="date"
                value={newDueDate}
                onChange={(e) => setNewDueDate(e.target.value)}
                className="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none text-sm"
              />
              <button
                onClick={handleAddTask}
                disabled={!newTitle.trim()}
                className="px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-gray-300 text-white rounded-lg text-sm font-medium transition-colors"
              >
                Save
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Auto-generated Reminders */}
      {autoReminders.length > 0 && (
        <div className="bg-gradient-to-r from-green-50 to-amber-50 dark:from-green-900/30 dark:to-amber-900/30 rounded-xl border border-green-200 dark:border-green-800 p-4 shadow-sm">
          <h2 className="text-lg font-semibold text-green-800 dark:text-green-200 mb-3 flex items-center gap-2">
            <Sprout className="w-5 h-5" />
            Seasonal Reminders
          </h2>
          <div className="space-y-2">
            {autoReminders.map((reminder) => (
              <div
                key={reminder.id}
                className="flex items-center gap-3 p-2 bg-white/70 dark:bg-gray-800/70 rounded-lg"
              >
                {reminderIcon(reminder.type)}
                <span className="text-sm text-gray-800 dark:text-gray-200 flex-1">
                  {reminder.title}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Overdue Tasks */}
      {overdueTasks.length > 0 && (
        <div className="bg-red-50 dark:bg-red-900/20 rounded-xl border border-red-200 dark:border-red-800 p-4 shadow-sm">
          <h2 className="text-lg font-semibold text-red-800 dark:text-red-200 mb-3 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5" />
            Overdue ({overdueTasks.length})
          </h2>
          <div className="space-y-2">
            {overdueTasks.map((task) => (
              <div
                key={task.id}
                className="flex items-center gap-3 p-2 bg-white/70 dark:bg-gray-800/70 rounded-lg"
              >
                <button onClick={() => toggleTask(task)}>
                  <Circle className="w-5 h-5 text-red-400 hover:text-red-600" />
                </button>
                <div className="flex-1">
                  <span className="text-sm text-red-800 dark:text-red-200">
                    {task.title}
                  </span>
                  {task.dueDate && (
                    <span className="text-xs text-red-500 ml-2">
                      Due {format(parseISO(task.dueDate), 'MMM d')}
                    </span>
                  )}
                </div>
                <button
                  onClick={() => task.id && deleteTask(task.id)}
                  className="text-gray-400 hover:text-red-500"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Today's Tasks */}
      <div className="bg-white dark:bg-gray-800 rounded-xl border border-green-200 dark:border-green-800 p-4 shadow-sm">
        <h2 className="text-lg font-semibold text-green-800 dark:text-green-200 mb-3 flex items-center gap-2">
          <CalendarDays className="w-5 h-5" />
          Today - {format(today, 'EEEE, MMMM d')}
        </h2>
        {todayTasks.length === 0 && noDueDateTasks.length === 0 ? (
          <p className="text-sm text-gray-500 dark:text-gray-400 italic">
            No tasks for today. Enjoy your garden!
          </p>
        ) : (
          <div className="space-y-2">
            {[...todayTasks, ...noDueDateTasks].map((task) => (
              <div
                key={task.id}
                className="flex items-center gap-3 p-2 hover:bg-green-50 dark:hover:bg-green-900/20 rounded-lg transition-colors"
              >
                <button onClick={() => toggleTask(task)}>
                  <Circle className="w-5 h-5 text-green-400 hover:text-green-600" />
                </button>
                <div className="flex-1">
                  <span className="text-sm text-gray-800 dark:text-gray-200">
                    {task.title}
                  </span>
                  {!task.dueDate && (
                    <span className="text-xs text-gray-400 ml-2">No due date</span>
                  )}
                </div>
                <button
                  onClick={() => task.id && deleteTask(task.id)}
                  className="text-gray-400 hover:text-red-500"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Upcoming Tasks */}
      {upcomingTasks.length > 0 && (
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-amber-200 dark:border-amber-800 p-4 shadow-sm">
          <h2 className="text-lg font-semibold text-amber-800 dark:text-amber-200 mb-3 flex items-center gap-2">
            <Clock className="w-5 h-5" />
            Upcoming ({upcomingTasks.length})
          </h2>
          <div className="space-y-2">
            {upcomingTasks
              .sort((a, b) => (a.dueDate ?? '').localeCompare(b.dueDate ?? ''))
              .map((task) => (
                <div
                  key={task.id}
                  className="flex items-center gap-3 p-2 hover:bg-amber-50 dark:hover:bg-amber-900/20 rounded-lg transition-colors"
                >
                  <button onClick={() => toggleTask(task)}>
                    <Circle className="w-5 h-5 text-amber-400 hover:text-amber-600" />
                  </button>
                  <div className="flex-1">
                    <span className="text-sm text-gray-800 dark:text-gray-200">
                      {task.title}
                    </span>
                    {task.dueDate && (
                      <span className="text-xs text-amber-600 dark:text-amber-400 ml-2">
                        {format(parseISO(task.dueDate), 'MMM d')}
                      </span>
                    )}
                  </div>
                  <button
                    onClick={() => task.id && deleteTask(task.id)}
                    className="text-gray-400 hover:text-red-500"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ))}
          </div>
        </div>
      )}

      {/* Completed Tasks */}
      {completedTasks.length > 0 && (
        <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl border border-gray-200 dark:border-gray-700 p-4 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-500 dark:text-gray-400 mb-3 flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5" />
            Completed ({completedTasks.length})
          </h2>
          <div className="space-y-2">
            {completedTasks.map((task) => (
              <div
                key={task.id}
                className="flex items-center gap-3 p-2 rounded-lg opacity-60"
              >
                <button onClick={() => toggleTask(task)}>
                  <CheckCircle2 className="w-5 h-5 text-green-500" />
                </button>
                <span className="text-sm text-gray-500 line-through flex-1">
                  {task.title}
                </span>
                <button
                  onClick={() => task.id && deleteTask(task.id)}
                  className="text-gray-400 hover:text-red-500"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Empty state */}
      {tasks.length === 0 && autoReminders.length === 0 && (
        <div className="text-center py-12">
          <Leaf className="w-12 h-12 text-green-300 mx-auto mb-3" />
          <h3 className="text-lg font-medium text-gray-500 dark:text-gray-400">
            Your garden dashboard is empty
          </h3>
          <p className="text-sm text-gray-400 dark:text-gray-500 mt-1">
            Add some plants and tasks to get started!
          </p>
        </div>
      )}
    </div>
  );
}
