import Dexie, { type Table } from 'dexie';
import type { Plant, GardenBed, Garden, Planting, JournalEntry, Task, AppSettings } from './types';
import { seedPlants } from './data/seedPlants';

export class PlotDatabase extends Dexie {
  plants!: Table<Plant, number>;
  gardens!: Table<Garden, number>;
  beds!: Table<GardenBed, number>;
  plantings!: Table<Planting, number>;
  journal!: Table<JournalEntry, number>;
  tasks!: Table<Task, number>;
  settings!: Table<AppSettings, number>;

  constructor() {
    super('PlotGardenPlanner');

    this.version(1).stores({
      plants: '++id, name, category, isCustom',
      gardens: '++id, name',
      beds: '++id, gardenId, name, type',
      plantings: '++id, plantId, bedId, status, year',
      journal: '++id, date, bedId, plantId',
      tasks: '++id, completed, dueDate, isAutoGenerated',
      settings: '++id',
    });
  }
}

export const db = new PlotDatabase();

export async function initializeDatabase() {
  const plantCount = await db.plants.count();
  if (plantCount === 0) {
    await db.plants.bulkAdd(seedPlants);
  }

  const settingsCount = await db.settings.count();
  if (settingsCount === 0) {
    await db.settings.add({
      units: 'metric',
      gardenName: 'My Garden',
      darkMode: false,
    });
  }

  const gardenCount = await db.gardens.count();
  if (gardenCount === 0) {
    await db.gardens.add({
      name: 'My Garden',
      gridWidth: 20,
      gridHeight: 15,
      scale: 0.5,
      scaleUnit: 'meters',
    });
  }
}
