export type PlantCategory = 'vegetable' | 'fruit' | 'herb' | 'flower';
export type FrostTolerance = 'hardy' | 'half-hardy' | 'tender';
export type SunRequirement = 'full-sun' | 'partial-shade' | 'shade';
export type PlantingStatus = 'planned' | 'sown' | 'transplanted' | 'growing' | 'harvesting' | 'finished' | 'failed';
export type WeatherType = 'sunny' | 'cloudy' | 'rainy' | 'frost' | 'snow' | 'windy' | 'overcast';
export type BedType = 'vegetable' | 'fruit' | 'flower' | 'herb' | 'mixed' | 'path' | 'structure';
export type UnitSystem = 'metric' | 'imperial';

export interface DateRange {
  start: string; // "MM-DD" format
  end: string;
}

export interface Plant {
  id?: number;
  name: string;
  botanicalName?: string;
  category: PlantCategory;
  sowIndoorRange?: DateRange;
  sowDirectRange?: DateRange;
  transplantRange?: DateRange;
  harvestRange?: DateRange;
  spacingRowCm: number;
  spacingPlantCm: number;
  sunRequirement: SunRequirement;
  wateringNotes: string;
  frostTolerance: FrostTolerance;
  companionPlants: string[];
  antagonists: string[];
  notes: string;
  isCustom?: boolean;
  indoorOnly?: boolean;
}

export interface GardenBed {
  id?: number;
  gardenId: number;
  name: string;
  type: BedType;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  color: string;
  points?: number[]; // for polygons
}

export interface Garden {
  id?: number;
  name: string;
  gridWidth: number;
  gridHeight: number;
  scale: number; // meters per grid square
  scaleUnit: 'meters' | 'feet';
}

export interface Planting {
  id?: number;
  plantId: number;
  bedId: number;
  dateSownIndoor?: string;
  dateSownDirect?: string;
  dateTransplanted?: string;
  dateHarvested?: string;
  status: PlantingStatus;
  quantity?: number;
  areaSqM?: number;
  notes: string;
  year: number;
}

export interface JournalEntry {
  id?: number;
  date: string;
  text: string;
  bedId?: number;
  plantId?: number;
  weather?: WeatherType;
  photoBlob?: Blob;
  photoDataUrl?: string;
}

export interface Task {
  id?: number;
  title: string;
  description?: string;
  dueDate?: string;
  completed: boolean;
  plantingId?: number;
  plantId?: number;
  isAutoGenerated?: boolean;
}

export interface AppSettings {
  id?: number;
  units: UnitSystem;
  gardenName: string;
  darkMode: boolean;
}

export type TabId = 'dashboard' | 'garden' | 'plants' | 'schedule' | 'journal';
